export const AGENT_TOOL_LABELS = {
  ask_questions: "Ask questions",
  bash: "Shell",
  brave_search: "Brave Search",
  browse_runner_directories: "Browse runner directories",
  continue_session: "Continue session",
  edit: "Edit files",
  explain_file: "Explain files",
  get_session_options: "Get session options",
  list_runners: "List runners",
  list_sessions: "List sessions",
  page_fetch: "Fetch page",
  parallel: "Parallel calls",
  read: "Read files",
  read_session: "Read session",
  reassign_session: "Reassign session",
  send_to_session: "Send to session",
  sleep: "Sleep",
  spawn_session: "Spawn session",
  stop_session: "Stop session",
  write: "Write files",
} as const;
